// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/forgetting-curve/ForgettingCurveBackground.tsx": () => import("../components/mockups/forgetting-curve/ForgettingCurveBackground.tsx"),
  "./components/mockups/forgetting-curve/ForgettingCurveDemo.tsx": () => import("../components/mockups/forgetting-curve/ForgettingCurveDemo.tsx"),
  "./components/mockups/landing-layouts/BentoGrid.tsx": () => import("../components/mockups/landing-layouts/BentoGrid.tsx"),
  "./components/mockups/landing-layouts/CinematicScreen.tsx": () => import("../components/mockups/landing-layouts/CinematicScreen.tsx"),
  "./components/mockups/landing-layouts/SplitScreenDock.tsx": () => import("../components/mockups/landing-layouts/SplitScreenDock.tsx"),
  "./components/mockups/synaptic-web/SynapticWeb.tsx": () => import("../components/mockups/synaptic-web/SynapticWeb.tsx"),
  "./components/mockups/synaptic-web/SynapticWebDemo.tsx": () => import("../components/mockups/synaptic-web/SynapticWebDemo.tsx"),
  "./components/mockups/vocabulous-hero/GlassmorphicHero.tsx": () => import("../components/mockups/vocabulous-hero/GlassmorphicHero.tsx"),
  "./components/mockups/vocabulous-hero/MinimalistBanner.tsx": () => import("../components/mockups/vocabulous-hero/MinimalistBanner.tsx"),
  "./components/mockups/vocabulous-hero/MinimalistHero.tsx": () => import("../components/mockups/vocabulous-hero/MinimalistHero.tsx"),
  "./components/mockups/vocabulous-hero/NeoBrutalistHero.tsx": () => import("../components/mockups/vocabulous-hero/NeoBrutalistHero.tsx"),
  "./components/mockups/vocabulous-hero/NeoRetroHero.tsx": () => import("../components/mockups/vocabulous-hero/NeoRetroHero.tsx"),
  "./components/mockups/vocabulous-hero/PitchDeckBanner.tsx": () => import("../components/mockups/vocabulous-hero/PitchDeckBanner.tsx"),
  "./components/mockups/vocabulous-landing/NeoBrutalistLogin.tsx": () => import("../components/mockups/vocabulous-landing/NeoBrutalistLogin.tsx")
};
